name: OpenOrcaLocal
task: text_generation
model: http://localhost:8080
pretrained_tokenizer: /home/mtman/Documents/Repos/yakwith.ai/models/Mistral-7B-OpenOrca
token: DUMMY
timeout: null
headers:
  Content-Type: application/json
cookies: null
stream: true
stream_chunk_size: 1
params:
  stop_sequences:
  - </s>
  - <s>
  - <|im_end|>
  - <|im_start|>
  max_new_tokens: 1024
  temperature: 0.9
  stream: ${..stream}