api:
  port: 8884  # Port that fastAPI runs on

# Credentials stored in .env
database:
  url: localhost:27017
  name: yak_test_db
  default_collection: cafes

assets:
  image_folder: /home/mtman/Documents/Repos/yakwith.ai/voice_chat/Images   #Ensure this matches the folder mapped to the mongodb volume in .env
  model_folder: /home/mtman/Documents/Repos/yakwith.ai/models   #Ensure this matches the folder mapped to the mongodb volume in .env

logging: 
  root_folder: /home/mtman/Documents/Repos/yakwith.ai/voice_chat/logs

ocr:
  url: http://localhost:8885/tesseract # Must ensure this matches the port specified in the environment variables used by docker-compose.